### ISSUE TITLE
申请加入Yommyko

### ISSUE THREAD

**Issue by 19958023** [darkflame0/feedback-vup.darkflame.ga#100]
Yommyko属于游戏区的套皮up主，性质类似于猫诺，asaki大人，c酱这样的。
希望能够加入统计。
B站UID是:14272337，名称是Yommyko

asaki大人，还有猫诺都添加了，类似的yommyko希望大佬们也能够加入，谢谢啦

**Comment by darkflame0** [comment]
其实除了C都不是我主动加的，都是切过一次虚拟主播区自动挂上的
