### ISSUE TITLE
不清楚现在B限和转播是否是算在一起的，如果是的话能否把B限和转播分开计算

### ISSUE THREAD

**Issue by wyj5230** [darkflame0/feedback-vup.darkflame.ga#13]
拜托了，DD们什么都会做的！大佬太忙的话我也可以帮忙

**Comment by darkflame0** [comment]
目前是一起算的，并且暂时没有分开算的打算，我不想强化【B限】这个概念

**Comment by wyj5230** [comment]
了解了，感谢回复。另外请问网站所使用的数据API是公开的吗？

**Comment by darkflame0** [comment]
“公开”是指什么

**Comment by wyj5230** [comment]
啊 就是采集数据所使用的的API是大家都能用的吗？如果是的话我也想尝试一下这样。因为我在网上没有搜到直播相关的B站API。如果是大佬自己做的轮子那就算拉

**Comment by darkflame0** [comment]
B站并没有公开可以直接获取这些数据的API，这边的数据都是通过实时收集B站的弹幕池然后再进行统计的，弹幕协议的话见https://github.com/lovelyyoshino/Bilibili-Live-API/blob/master/API.WebSocket.md

**Comment by wyj5230** [comment]
感谢分享，十分有用！还想请教2点：API文档中没有找到营收信息，是通过金瓜子或者礼物API累加计算得出的吗？还有直播总时长是怎样统计的呢？

**Comment by darkflame0** [comment]
弹幕池中会有礼物、SC信息，收集后计算就可以了
总时长就是每次直播的时长加起来
