### ISSUE TITLE
可否请大佬补全一下

### ISSUE THREAD

**Issue by accelarater** [darkflame0/feedback-vup.darkflame.ga#25]
花寄女子寮成员好像没有在记录里，能不能请大佬补充一下，谢谢

**Comment by darkflame0** [comment]
有的啊，看不到大概是没进榜，你可以直接通过组织筛选查到

**Comment by accelarater** [comment]
大佬你好！
我们现在正在做一个关于虚拟主播的经济学实证研究，参加了学生的创新项目，想问问能不能授权使用你网站的数据呢？
谢谢
