### ISSUE TITLE
数据使用申请

### ISSUE THREAD

**Issue by accelarater** [darkflame0/feedback-vup.darkflame.ga#26]
大佬你好
我们这边正在做一个有关虚拟主播的经济学实证分析项目，想问问你能不能使用您网站的数据，作为研究的素材呢？我们是一个学生团队，这个项目正在参加一个创新项目评比，如果大佬能够帮助我们的话，我们的研究会顺利很多。
谢谢大佬

**Comment by darkflame0** [comment]
网站上可以拿到的数据随便用
