### ISSUE TITLE
期望详细中添加更多数据

### ISSUE THREAD

**Issue by FlameRat** [darkflame0/feedback-vup.darkflame.ga#41]
分析数据时，有时候会用到付费粉丝比、舰队粉丝比，但是这边少一些数据，还得去其他地方扒数据，如果能再添加一些数据项就太好了
比较重要的：
粉丝数量、付费30元及以上人数、舰队人数

**Comment by darkflame0** [comment]
粉丝数量、舰队人数跟弹幕数据关联性不强，我这边没有做录入，建议去其它地方收集
