### ISSUE TITLE
增加每日同接（互动） 峰值统计

### ISSUE THREAD

**Issue by wardsong** [darkflame0/feedback-vup.darkflame.ga#5]
希望能像vnuma那样增加每日同接（互动） 峰值的统计
![IMG_20200301_003237](https://user-images.githubusercontent.com/61629107/75611292-3010a880-5b54-11ea-8d0a-bee0c3ece70a.jpg)

**Comment by darkflame0** [comment]
B站没有实时的人数显示，人气由于倍率关系也不能作准
目前能算的都是某个时段的数据，如果要算一个“峰值”出来，具体应该是什么样的峰值呢？

**Comment by darkflame0** [comment]
重新理解了一下，如果是24小时的话，目前有单日的榜单，如果要按单次直播算的话，实现上还要考虑一下
月统计可以考虑加一个最高单日单日数据

**Comment by darkflame0** [comment]
先加了个最高单日统计，基于单次直播的日后再说

**Comment by darkflame0** [comment]
已添加基于直播记录的统计
