### ISSUE TITLE
好奇一月份之前的营收榜单之类的数据

### ISSUE THREAD

**Issue by ZTMC** [darkflame0/feedback-vup.darkflame.ga#6]
希望能查看一下一些2019的数据, 若没有记录的话就算了吧. 非常感谢!

**Comment by darkflame0** [comment]
我这边没有，如果有数据可以提供或者渠道希望可以联系我

**Comment by darkflame0** [comment]
我这边不全，只有几个月，而且因为之前系统不成熟，记录可能很不全，就不放了，如果有稍微完整一些的原始数据，可以提供数据或者渠道希望可以联系我
