### ISSUE TITLE
关于未收录B站vtb 幼薇喵_ゆいnya 的直播间的反馈

### ISSUE THREAD

**Issue by LEOkrupp** [darkflame0/feedback-vup.darkflame.ga#60]
幼薇喵的直播间 https://live.bilibili.com/22500194

**Comment by LEOkrupp** [comment]
【【新衣披露】幼薇喵3千粉新衣披露~-哔哩哔哩】https://b23.tv/1ALDeC

**Comment by LEOkrupp** [comment]
【【幼薇喵个人介绍】初次见面，请多关照-哔哩哔哩】https://b23.tv/6K4HxO

**Comment by darkflame0** [comment]
已经有了啊  开播应该能找到的
