### ISSUE TITLE
服务器还没修好吗

### ISSUE THREAD

**Issue by calcxx** [darkflame0/feedback-vup.darkflame.ga#68]
Host Error都已经3天了，这个项目是停止运营了吗……
希望能回复一下，至少大家也知道是个什么情况

**Comment by darkflame0** [comment]
服务器刚恢复，现在在导入数据，估计明天能好吧
![image](https://user-images.githubusercontent.com/22924199/140305844-5bb8645f-687d-4978-ad64-ee7e18820b16.png)
