### ISSUE TITLE
2021-12月榜组织汇总数据和明细数据对不上

### ISSUE THREAD

**Issue by kongdeguiji111** [darkflame0/feedback-vup.darkflame.ga#79]
拿A-SOUL举例，月榜选组织时营收 3,150,065 ；然而月榜看个人再筛选A-SOUL，5个账号营收相加 3,448,732 ，直播时长和弹幕这种明细和汇总也对不上。其他组着这种个人明细和组织汇总数据似乎也是这问题，目前只发现2021-12有这个问题。

**Comment by darkflame0** [comment]
有缓存，如果数据更新失败了就拿的是前一天的数据，所以少了一天的量，我看一下

**Comment by darkflame0** [comment]
好了，那天数据量大了，给的内存不够用了，所以失败了
