### ISSUE TITLE
建议更新一下数据

### ISSUE THREAD

**Issue by clhaaaa** [darkflame0/feedback-vup.darkflame.ga#8]
收录的主播组织和主播都有点旧，比如说早稻叽已经转到chaoslive了。

**Comment by ZTMC** [comment]
这方面资料可以看看萌百, 例如PSP的是这个
https://zh.moegirl.org/P-SP

**Comment by clhaaaa** [comment]
再补充个数据来源 https://vtbs.moe/detail
需要更新的数据
chaoslive成员：早稻叽 uid:1950658
                          牛牛子 uid:34194547
                         白夜真宵 uid:504694462
                         白夜天存 uid:502916449

**Comment by darkflame0** [comment]
已添加
