### ISSUE TITLE
没有星律动？

### ISSUE THREAD

**Issue by 55211015** [darkflame0/feedback-vup.darkflame.ga#89]
组织那边没有星律动的唐九夏、吉诺儿kino的数据

**Comment by darkflame0** [comment]
你给个列表，包括uid、roomid

**Comment by 55211015** [comment]
Nebula Beat:
https://space.bilibili.com/1795366254

唐九夏:
https://space.bilibili.com/1219196749
直播間:
https://live.bilibili.com/23303212

吉诺儿kino:
https://space.bilibili.com/1383815813
直播間:
https://live.bilibili.com/23221095

**Comment by 55211015** [comment]
同属於星律动

战斗吧歌姬官方账号
https://space.bilibili.com/364225566/

罗兹Blazing
https://space.bilibili.com/1315573139
直播间
https://live.bilibili.com/14578426
